### PR TITLE
updated manifest to have 1.5

### PR DESCRIPTION
**Pull request by longnguyen11288**

### CODE REVIEW

**Comment by flavorjones** [comment]
@longnguyen11288 Thank you for this contribution!

For future reference, please do make sure your PR is being rebased from the `develop` branch, and not the `master` branch.

This looks good, and I'll schedule this work!

**Comment by flavorjones** [comment]
I merged your commit manually into the `develop` branch as 02cad58

Thank you so much for the commit! This will be in go-buildpack v1.6.0. Here's the story to cut that release: https://www.pivotaltracker.com/story/show/101628236

**Comment by longnguyen11288** [comment]
Ah crap. I'm pretty sure this is like 4-5 time I've been yelled at for
this. Sorry Mike.

**Comment by flavorjones** [comment]
v1.6.0 is out! Thanks again.

**Pull request closed without merging**
