### PR TITLE
Improve run example in markdown so it's readable

### PR DESCRIPTION
**Pull request by squeedee**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
Improves readability of the content in the example go app readme

* An explanation of the use cases your change solves

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [ ] I have made this pull request to the `develop` branch

* [ ] I have added an integration test

### CODE REVIEW

**Comment by squeedee** [comment]
I'm sorry I somehow found the 'submit' keyboard shortcut with fat fingers - this is pointing to master not develop.

**Comment by Zanadar** [comment]
@squeedee if you could sign the CLA, I’ll merge this ASAP. Looks good. Thanks for contributing.

**Comment by dfreilich** [comment]
@squeedee Thanks for the additions! As mentioned above, if you could sign the CLA, that would be great.

**Comment by squeedee** [comment]
Honestly I tried, I'll try again and see if someone at work responds

**Comment by squeedee** [comment]
Sorry that took so long

**Pull request merged**
