### PR TITLE
Support custom package spec with native vendoring.

### PR DESCRIPTION
**Pull request by jmcarp**
To allow `go install` paths that differ from the default of `.`, and for parity with glide vendoring, respect the `GO_INSTALL_PACKAGE_SPEC` environment variable with native vendoring.

* [x] I have viewed signed and have submitted the Contributor License Agreement
* [x] I have made this pull request to the `develop` branch

### CODE REVIEW

**Comment by RochesterinNYC** [comment]
Hey @jmcarp, this change looks like it makes sense. However, we'll have to create an integration spec and possibly a fixture app before we can merge this in.

We'll be doing that work as part of this story: https://www.pivotaltracker.com/story/show/128292483

**Comment by jchesterpivotal** [comment]
Hi @jmcarp, we picked this story up today and started spelunking to work out how we want to test it.

We noticed an interesting thing.

In the `go_nativevendoring` codepath, the ultimate value of `$pkgs` is derived from `$name`, which is affected by the variable `$GOPACKAGENAME`.

In the `glide` codepath it uses the two lines you're proposing to add to the `go_nativevendoring` code.

The `glide` codepath, like `go_nativevendoring`, derives `$pkgs` from `$name`, and `$name` is affected by the variable `$GO_INSTALL_PACKAGE_SPEC`.

So it seems to us that we have an example of convergent evolution: each codepath providing independent mechanisms to specify a package name that ultimately gets passed in to `go install`.

We're wondering if you noticed this?

We only just noticed ourselves and our instinct is to pick one and kill the other, but if you have any feedback on that, please let us know. Our expectation is that `$GOPACKAGENAME` would emerge as the surviving name, because it's [already in the public documentation](http://docs.cloudfoundry.org/buildpacks/go/index.html#pushing_Apps_with_native_Go_vendoring). 

We could probably adopt the nice warning that `handleDefaultPkgSpec()` emits during the `glide` codepath as well.

**Comment by jmcarp** [comment]
@jchesterpivotal: sorry, I'm not following--in `go_nativevendoring`, `pkgs` is currently hard-coded to `"."`, right? Also, the roles of the `name` and `pkgs` variables seem different--`name` controls what gets copied to `$GOPATH`, and `pkgs` controls what gets passed to `go build`. Anyway, definitely agree that environment variables should do the same thing across different package managers if possible.

**Comment by RochesterinNYC** [comment]
Yup, never mind. It seems you're correct @jmcarp. Would you mind adding an integration spec and app fixture for this PR? Thanks!

**Comment by jmcarp** [comment]
Sure, added a test @RochesterinNYC

**Comment by RochesterinNYC** [comment]
Thanks for the pull request @jmcarp. The test looks solid and we've verified it locally as well. Cheers!

**Pull request merged**
