### PR TITLE
Support for Dynatrace monitoring on the Go buildpack

### PR DESCRIPTION
**Pull request by DTMad**
* A short explanation of the proposed change:
Added support for Dynatrace monitoring for Go applications - similar to what we already have for other buildpacks like the NodeJs buildpack.

For further information how to use see:
https://www.dynatrace.com/support/help/shortlink/cloud-foundry

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [x] I have added an integration test

### CODE REVIEW

**Comment by kardolus** [comment]
@DTMad Thanks! We will prioritize this.

**Comment by danirabiser** [comment]
Hi @kardolus, thanks for prioritizing our PR. 
Is there anything we can do to help resolving the conflicts in go.sum?

Thanks,
Daniela

**Comment by kardolus** [comment]
@danirabiser No worries, we will deal with the go.sum issue on our end. Usually I just delete the file and then regenerate it (go mod tidy / go mod download). Not sure what the elegant solution is for handling go.sum issues in a git repo.

**Comment by danirabiser** [comment]
@kardolus Thanks for your quick reply and thanks for taking care of resolving the conflict on your end. Then we'll be eagerly waiting for our PR to be merged ;) :D 

Thanks,
Daniela

**Comment by kardolus** [comment]
@danirabiser merged! Thanks for your patience

**Comment by aloismayr** [comment]
Hi @kardolus Thanks for merging the PR into the dev branch. This is one step closer to our goal :) 
Do you have a rough estimate when this PR will be made available through a new release?

**Pull request merged**
