### PR TITLE
Converts integration suite to use switchblade

### PR DESCRIPTION
**Pull request by ryanmoran**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
This should allow the buildpack integration suite to run against a Docker daemon instead of a full Cloud Foundry. In theory, this should make running the integration suite a bit easier.

* [x] I have viewed signed and have submitted the Contributor License Agreement
* [x] I have made this pull request to the `develop` branch
* [x] I have added an integration test

### CODE REVIEW

**Review by ForestEckhardt — CHANGES_REQUESTED** [review]
Could you update the README with switchblade testing information, like how to run on the docker vs CF?

**Comment by ForestEckhardt** [comment]
I am currently running local tests. My next question is whether or not this will work with the current CI testing job? It looks like some changes would need as there have been some changes made to the integration script.

**Comment by ryanmoran** [comment]
It will work. The 2 flags I added are optional and default to values that "just work" with CI.

**Comment by ForestEckhardt** [comment]
Sweet as soon as I see local green I am happy to approve and merge

**Review by ForestEckhardt — APPROVED** [review]

**Pull request merged**
